config/routes.rb
What2EatTonight::Application.routes.draw do
  
  resource :session, only: [:new, :create, :destroy]

  get "users/" => "users#index", as: :user
  get "users/new" => "users#new", as: :new_user
  post "users" => "users#create"
  get "users/edit/:id" => "users#edit", as: :users_edit
  patch "users/:id" => "users#update", as: :users_update
  post "users/show" => "users#show"

  resources :comments

  resource :images
  post "images/" => "images#email", as: :email

  root "images#index"

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :text, type: String

  belongs_to :user

end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Paperclip
  field :cuisine, type: String
  field :restaurant, type: String
  field :location, type: String

  belongs_to :user

  has_mongoid_attached_file :image
  
  validates_presence_of :image
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_presence_of :cuisine
  validates_presence_of :restaurant
  validates_presence_of :location


end

app/models/user.rb
class User

  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :name

  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  
  validates :password, length: { minimum: 6 }

  has_many :comments
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    if !current_user
      redirect_to root_path
      return
    end
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    if !current_user
      redirect_to home_path
      return
    end
    comment = current_user.comments.new(params.require(:comment).permit(:text))
    if comment.save
      redirect_to new_comment_path
    else
      render 'new'
    end
  end

  def edit
    if !current_user
      redirect_to root_path
      return
    end
    @comment = Comment.find(params[:id])
  end

  def update
    if !current_user
      redirect_to home_path
      return
    end
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params.require(:comment).permit(:text))
      redirect_to new_comment_path
    else
      render 'edit'
    end
  end

  # def show
  #   @comment = Comment.find(params[:id])
  # end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to new_comment_path
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def index
    @images = Image.all
  end

  def new
    if !current_user
      redirect_to root_path
      return
    end
    @image = Image.new
  end

  def create
    if !current_user
      redirect_to root_path
      return
    end
    image = current_user.images.new(params.require(:image).permit(:cuisine, :restaurant, :location, :image))
    if image.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @current_user = current_user
    # Tell the UserMailer to send email linking to edit password page
    UserMailer.email_location(@current_user).deliver
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #present an empty login form
    @user = User.new
  end

  def create
    #Find the user that is trying to login
    u = User.where(email: params[:user][:email]).first
    #prove that they are indeed who they say they are (password)
    if u && u.authenticate(params[:user][:password])
      #store as a cookie in browser, their id
      #indicating that they are logged in
      session[:user_id] = u.id.to_s
      redirect_to root_path
    elsif u == nil
      flash[:error]="Email and Password do not match our database"
      #go back to the login page
      redirect_to new_session_path
    elsif u && !u.authenticate(params[:user][:password])
      flash[:error]="Password does not match our database"
      #go back to the login page
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def yelp
    parameters = { term: 'restaurant', limit: 10 }
    @response = Yelp.client.search('San Francisco', parameters)
    @data =  @response.businesses[0].image_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      u = User.where(email: params[:user][:email]).first
      session[:user_id] = u.id.to_s
      # Tell the UserMailer to send email linking to edit password page
      UserMailer.forgot_password(@user).deliver
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(page_title)
    base_title = "Testing: "
    if page_title.empty?
      "No Page Title!"
    else
      "#{base_title}#{page_title}"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_post.html.erb
<div>
  <h2><%= link_to comment.text, post_path(post) %></h2>
 
      <div class="post"><h4><span><%= c.user.name %></span></h4><div class="pcontent">"<%= c.text %>"<sub class="time">
      <!-- Edit link (only shown if you are the user that created it) -->
      <%= link_to "Edit", edit_comment_path(c) if (current_user == c.user) %></sub></div><%= c.created_at.strftime("%I:%M%p, %b %d 20%y ") %></div>
    <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Edit your Comment</h1>

<p><%= "\"#{@comment.text}\"" %></p>

<div class="col-md-6 col-md-offset-3">
  <%= form_for @comment, html:{class: "well well-lg"} do |c| %>
    <%= c.text_field :text, class: "form-control input-lg" %>

    <%= c.submit "Submit Changes", class: "btn btn-block btn-primary btn-lg" %>

  <% end %>

  <button class="btn btn-danger">
    <%= link_to "Delete", comment_path(@comment), method: :delete %>
  </button>

  <%= link_to "Back to Comments", new_comment_path %>
</div>

app/views/comments/new.html.erb
<div class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
  </br>
  <!-- New Comment Modal Button -->
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Add Comment
  </button>

  <!-- New Comment Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- <div class="modal-body"> -->
          <%= form_for @comment, html:{class: "container"} do |f| %>
          <fieldset class="inputs">
            <%= f.text_field :text, required:true, class: "text-box", placeholder: "Say Something..." %>
          </fieldset>
          <fieldset class="actions">
            <%= f.submit "POST", class: "submit" %>
          </fieldset>
          <% end %>
      </div>
    </div>
  </div>
  <!-- End of New Comment Modal -->

  <!-- List of all the comments -->
  <div class="post-container" id="overflow">
    <% @comments.reverse.each do |c| %>
    <div class="post">
      <h4><span><%= c.user.name %></span></h4>
      <div class="pcontent">"<%= c.text %>"<sub class="time">
      <!-- Edit link (only shown if you are the user that created it) -->
      <%= link_to "Edit", edit_comment_path(c) if (current_user == c.user) %></sub>
      </div>
    <%= c.created_at.strftime("%I:%M%p, %b %d 20%y ") %>
    </div>
    <% end %>
  </div>
</div>

app/views/images/index.html.erb
<div id="background-carousel">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="item active" style="background-image:url(<%= asset_path "homepage.jpg" %>)"></div>
        <% @images.shuffle.each do |i| %>
          <div class="item" style="background-image:url(
          <%= i.image.url(:original) %>)" ng-click="modal('<%= i.cuisine %>', '<%= i.restaurant %>', '<%= i.location %>', '<%= i.user.name %>')" data-toggle="modal" data-target="#myModal"></div>
        <% end %> 
      </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title black" id="myModalLabel">Looks like you should get some {{cuisine}} tonight</h1>
      </div>
      <div class="modal-body">
        <h3 class="black">This particular image came from {{restaurant}}</h3>
        <div class="map-wrapper">
          <div id="map-canvas"></div>
        </div>
        <h4 class="black">{{location}}</h4>
        <h6 class="black">Contributed by: {{user}}</h6>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Fuck this Food</button>
        <%= button_to "Email me Location", email_path, method: :get, class: "btn btn-primary pull-right" if current_user%>
      </div>
    </div>
  </div>
</div>

app/views/images/new.html.erb
<div class="col-sm-6 col-sm-offset-3">

<h1>Add Food Image to Our Site</h1>

<%= form_for @image, {url: images_path(@image), html:{class: "well well-lg"}}  do |f| %>

  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:
      </h2>

      <ul class="list-group">
      <% @image.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- CUISINE FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      <%= f.text_field :cuisine, required:true, :class => "form-control input-lg", placeholder: "Cuisine Type..." %>
  </div>

  <!-- RESTAURANT FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
      <%= f.text_field :restaurant, required:true, :class => "form-control input-lg", placeholder: "Restaurant Name..." %>
  </div>

  <!-- LOCATION FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-road"></i></span>
      <%= f.text_field :location, required:true, :class => "form-control input-lg", placeholder: "Restaurant Address..." %>
  </div>

  <!-- IMAGE FILE FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
      <%= f.file_field :image, required:true %>
  </div>

  <!-- SUBMIT BUTTON -->
  <div class="form-group">
      <%= f.submit "Upload Image", :class => "btn btn-block btn-primary btn-lg"%>
    </button>
  </div>


<% end %>

</br>


</div>

app/views/images/show.html.erb
<h1>EMAILED</h1>

app/views/layouts/_menu.html.erb
<!-- MENU -->
  <div class="menu-container">
      <div class="col-xs-9 menu">
        <%= link_to image_tag("WE2T_logo.png", class: "logo"), root_path, method: :get %>
        <h1>MENU</h1>
          <p><%= "Welcome, #{current_user.name}!" if current_user%></p>
          <p><%=link_to "Log in", new_session_path, class: "btn btn-primary" if !current_user%></p>
          <p><%=link_to "Register", new_user_path, class: "btn btn-warning" if !current_user%></p>
          <p><%= link_to "Logout", session_path, class: "btn btn-danger", method: :delete if current_user%></p>
          </br>
          <p><%= "Why register today?" if !current_user %></p>
          <p><%= "Access to our Comments Gallery!" if !current_user %></p>
          <p><%= "Ability to add your own restaurant food pics!" if !current_user %></p>
          <h2><%= link_to "Add an New Image", new_images_path, class: "btn btn-success" if current_user%></h2>
          <h2><%= link_to "Comments Gallery", new_comment_path, class: "btn btn-info" if current_user%></h2>
      </div>
      <div class="col-xs-3 menu-hover">
      </br>
        <button type="button" class="btn btn-default pull-left visible-xs">
          <span class="glyphicon glyphicon-th-large"></span>
        </button>
      </div>
  </div>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "wet", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.16/angular.js" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBGTe0V5uTVneDnr5Neghjh-w2BUZBuhXY" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="wetApp">
<head>
  <title>What2EatTonight</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta charset="utf-8">
  <meta name="description" content="Visual selection of what to eat tonight. A visual representation of food near you.">
  <meta name="author" content="Ian Goldfarb">
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
</head>
<body ng-controller="wetController">

  <%= render 'layouts/menu' %>

  <!-- User Name -->
  <h3 class= "user pull-right"><%= "#{current_user.name}" if current_user%></h3>

  <!-- IMAGES/FORMS YIELD -->
  <div></div>
  <div class="container-fluid">
    <div class="row">

        <%= yield %>


    </div>
  </div>

  <!-- CONTACT -->
  <div class="contact-container">
    <button type="button" class="btn btn-default pull-left">
      <span class="glyphicon glyphicon-star"></span>
    </button>
    <p class="creator"> Created by: <a href="https://github.com/Superman2971">Ian Goldfarb</a></p>
  </div>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit Password</h1>

<div class="col-sm-6 col-sm-offset-3">

<%= form_for @user,:url => users_update_path, html:{class: "well well-lg"} do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited your registration:
      </h2>

      <ul class="list-group">
      <% @user.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1>PASSWORD CHANGE for: <%=@user.name%></h1>

  <!-- PASSWORD FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
      <%= f.password_field :password, required:true, class: "form-control input-lg", placeholder: "New Password Here..." %>
  </div>

  <!-- PASSWORD CONFIRMATION FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
      <%= f.password_field :password_confirmation, required:true, class: "form-control input-lg", placeholder: "New Password Confirmation..." %>
  </div>

  <!-- SUBMIT BUTTON -->
  <div class="form-group">
      <%= f.submit "Login", class: "btn btn-block btn-primary btn-lg"%>
  </div>

<% end %>


</div>

app/views/users/index.html.erb
<h1>All of our Users!</h1>

<% @user.each do |u| %>
  <h3><%= u.name %></h3>
<% end %>

app/views/users/new.html.erb
<h1>Sign-up Page</h1>

<div class="col-sm-6 col-sm-offset-3">

<%= form_for @user, html:{class: "well well-lg"} do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited your registration:
      </h2>

      <ul class="list-group">
      <% @user.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- NAME FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <%= f.text_field :name, required:true, class: "form-control input-lg", placeholder: "Name Here..." %>
  </div>

  <!-- EMAIL FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <%= f.text_field :email, required:true, class: "form-control input-lg", placeholder: "Email Here..." %>
  </div>

  <!-- PASSWORD FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
      <%= f.password_field :password, required:true, class: "form-control input-lg", placeholder: "Password Here..." %>
  </div>

  <!-- PASSWORD CONFIRMATION FIELD -->
  <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
      <%= f.password_field :password_confirmation, required:true, class: "form-control input-lg", placeholder: "Password Confirmation..." %>
  </div>

  <!-- SUBMIT BUTTON -->
  <div class="form-group">
      <%= f.submit "Login", class: "btn btn-block btn-primary btn-lg"%>
  </div>

<% end %>


</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>